server:
  port: 8000
  host: "0.0.0.0"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

admin:
  password: "admin123"
  api_key: ""

db:
  type: "mysql"
  mysql:
    host: "mysql"
    port: 3306
    user: "root"
    password: "codefreemax"
    name: "kiro_client"
